#pragma once

enum XACT_WAVEBANK_AUDIOBANK : unsigned int
{
    XACT_WAVEBANK_AUDIOBANK_BRAVESPACEEXPLORERS = 0,
    XACT_WAVEBANK_AUDIOBANK_COINSFX = 1,
    XACT_WAVEBANK_AUDIOBANK_IMPACTSFX1 = 2,
    XACT_WAVEBANK_AUDIOBANK_ROCKETBOOSTENGINELOOP = 3,
};

#define XACT_WAVEBANK_AUDIOBANK_ENTRY_COUNT 4
